apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-rag-bot
  labels:
    app: edu-rag-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edu-rag-bot
  template:
    metadata:
      labels:
        app: edu-rag-bot
    spec:
      containers:
        - name: edu-rag-bot
          image: crpi-he7mqvhihpnvi08o.cn-shanghai.personal.cr.aliyuncs.com/my-rag-project/rag-service:latest
          imagePullPolicy: Always
          envfrom:
            - secretRef:
                name: edu-rag-bot-secret
          ports:
            - containerPort: 7860
