apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
  labels:
    app: rag-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
        - name: backend
          image: crpi-he7mqvhihpnvi08o.cn-shanghai.personal.cr.aliyuncs.com/my-rag-project/rag-service:36eb991d03e1d02f51eb68aa7a03889da2975bec
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: edu-rag-bot-secret
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rag-backend-svc
spec:
  selector:
    app: rag-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-frontend
  labels:
    app: rag-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-frontend
  template:
    metadata:
      labels:
        app: rag-frontend
    spec:
      containers:
        - name: frontend
          image: crpi-he7mqvhihpnvi08o.cn-shanghai.personal.cr.aliyuncs.com/my-rag-project/rag-service:36eb991d03e1d02f51eb68aa7a03889da2975bec
          imagePullPolicy: Always
          command: ["python", "ui.py"]
          env:
            - name: API_URL
              value: "http://rag-backend-svc/api/chat"
          ports:
            - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: rag-frontend-svc
spec:
  selector:
    app: rag-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
