apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
  labels:
    app: rag-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
        - name: backend
          image: crpi-he7mqvhihpnvi08o.cn-shanghai.personal.cr.aliyuncs.com/my-rag-project/rag-service:a47fca46101c1cae82bdb1b0d6e1ee1f86245fd3
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: edu-rag-bot-secret
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rag-backend-svc
  namespace: edu-rag-bot
  labels: 
    app: rag-backend
spec:
  selector:
    app: rag-backend
  ports:
    - name: http-metrics
      protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-frontend
  labels:
    app: rag-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-frontend
  template:
    metadata:
      labels:
        app: rag-frontend
    spec:
      containers:
        - name: frontend
          image: crpi-he7mqvhihpnvi08o.cn-shanghai.personal.cr.aliyuncs.com/my-rag-project/rag-service:a47fca46101c1cae82bdb1b0d6e1ee1f86245fd3
          imagePullPolicy: Always
          command: ["python", "ui.py"]
          env:
            - name: API_URL
              value: "http://rag-backend-svc/api/chat"
            - name: UPLOAD_URL
              value: "http://rag-backend-svc/api/upload"
          ports:
            - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: rag-frontend-svc
spec:
  selector:
    app: rag-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rag-backend-monitor
  namespace: edu-rag-bot      # <--- 明确指明自己在哪
  labels:
    release: prometheus       # <--- 对接 Prometheus 的接头暗号
spec:
  namespaceSelector:          
    matchNames:
      - edu-rag-bot           # <--- 强行命令它去这个命名空间里抓人！
  selector:
    matchLabels:
      app: rag-backend        # <--- 去抓带有这个身份证的 Service！
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
